try{
    throw new Error('Nope! Not gonna happen!');
}
catch(e){
    console.log(e);
}